Switch from pallet-assets to orml-tokens
virto-network/virto-node pull request #129
Opened 2021-09-14 09:01 UTC by stanly-johnson

Remove all usage of pallet-assets and replace with orml-tokens
Related #113

2021-09-14 09:09 UTC, olanod requested changes

2021-09-14 09:09 UTC, olanod commented on runtime/src/lib.rs
> +                    Collateral: orml_tokens::<Instance2>::{Config<T>, Event<T>, Pallet, Storage},
Can we still call the token collections `Assets` and `Fiat`? `Assets` being used for communities tokens and foreign assets like the `kUSD` and `Fiat` for the fungibles that can be traded via the escrow pallet? we no longer will "collateralize" the creation of other asset like previously with the `USDv`.

2021-09-14 12:34 UTC, olanod approved these changes

2021-09-14 12:36 UTC, olanod commented
LGTM! Nice work, lets make CI happy and feel free to merge, more clean-up and improvements can come in next iterations 👍🏽

2021-09-17 02:48 UTC, stanly-johnson commented
@olanod The CI is all good in my local. Could you pls take a look, the error is related to clippy not available for latest nightly
`error: 'cargo-clippy' is not installed for the toolchain 'nightly-2021-08-17-x86_64-unknown-linux-gnu'`

2021-09-17 08:28 UTC, olanod approved these changes

2021-09-18 02:15 UTC, merged