[Payments pallet] - Create, release and cancel
virto-network/virto-node pull request #282
Opened 2023-08-21 15:45 UTC by darkforest0202

Related #280 #247 

Phase 1: Basic functionality
Use case: A buys a product from B using the pallet and a payment is placed using the pay functionality. At this point, balance is transferred to A but freezed. This allows B to see the new balance but not available for it's use until A confirms the product was received.
Then when A confirms that product was received, it free the balance by calling release. cancel is trivial.

pay -> (add payment_detail type (enum) )
release
cancel

---

Also an enhanced version of the fees was introduced:

```rust
#[derive(Clone, Encode, Decode, Eq, PartialEq, Default, MaxEncodedLen, TypeInfo, Debug)]
pub struct Fees<BoundedFeeDetails> {
	pub sender_pays: BoundedFeeDetails,
	pub beneficiary_pays: BoundedFeeDetails,
}
```

where `BoundedFeeDetails` could be typed like this:
```rust
pub type BoundedFeeDetails<T> =
	BoundedVec<(<T as frame_system::Config>::AccountId, BalanceOf<T>), <T as Config>::MaxFees>;
```

and the `FeeHandler` now retrieves:

```
pub trait FeeHandler<T: pallet::Config, BoundedFeeDetails> {
	/// Get the distribution of fees to marketplace participants
	fn apply_fees(
		sender: &T::AccountId,
		beneficiary: &T::AccountId,
		amount: &BalanceOf<T>,
		remark: Option<&[u8]>,
	) -> Fees<BoundedFeeDetails>;
}
```

Next steps:

- Add Ids to the Payments storage item being a `StorageNMap` type with keys : sender, beneficiary, payment_id
- Add benchmarking.

2023-08-21 16:56 UTC, darkforest0202 commented
I need to solve some clippy complains btw.

2023-08-22 11:14 UTC, olanod requested changes
Great job! I'm excited to see the pallet in action.
Left several comments for changes that were easier to realize once seeing the code.

2023-08-22 11:14 UTC, olanod commented on pallets/payments/src/types.rs
> +		amount: &BalanceOf<T>,
AssetId is probably necessary for fee handlers to determine the right fees

2023-08-24 10:49 UTC, darkforest0202 commented on pallets/payments/src/lib.rs
> +		incentive_percentage: Percent,
hmm what would be the gain of making this change?

2023-08-25 18:46 UTC, olanod approved these changes

2023-08-26 13:20 UTC, merged